# 1. 
SELECT * FROM STAFF; ALTER TABLE STAFF DROP COLUMN PICTURE;
# 2
SELECT * FROM CUSTOMER WHERE FIRST_NAME = "TAMMY";
SELECT * FROM STAFF; INSERT INTO STAFF VALUES(3, "Tammy", "Sanders", 79, "TAMMY.SANDERS@sakilacustomer.org", 2, 1, "Tammy", "", "2006-02-16 00:00:00");
#INSERT INTO staff;FROM CUSTOMER;
# 3. 
SELECT * FROM RENTAL;    
SELECT  MAX(RENTAL_ID) FROM RENTAL;    
SELECT * FROM INVENTORY WHERE FILM_ID =1;
SELECT * FROM FILM WHERE TITLE = "Academy Dinosaur";
SELECT * FROM CUSTOMER WHERE LAST_NAME = "Hunter";    
SELECT * FROM STAFF;
INSERT INTO RENTAL VALUES(16050, "2022-01-05 22:30:00", 1, 130, "2022-02-04 22:00;00", 1, "2022-02-05 12:00;00");
SELECT * FROM RENTAL ORDER BY RENTAL_ID DESC LIMIT 5;
# 4
SELECT DISTINCT ACTIVE FROM CUSTOMER;
SELECT * FROM CUSTOMER LIMIT 5;
SELECT COUNT(ACTIVE) FROM CUSTOMER WHERE ACTIVE =0;
    CREATE TABLE Deleted_Users (
	customer_id INT(11) DEFAULT NULL,
    email TEXT,
    create_date DATETIME
);
SELECT * FROM DELETED_USERS;
SELECT COUNT(CUSTOMER_ID) FROM 	DELETED_USERS;
INSERT INTO DELETED_USERS (customer_id, email, create_date)
SELECT customer_id, email, create_date FROM customer WHERE ACTIVE =0;
